    - name: app setup
      include_role:
        name: common
        tasks_from: app_setup

    - name: maven install
      include_role:
        name: common
        tasks_from: maven


    - name: system setup
      include_role:
        name: common
        tasks_from: systemd  
    
    - name: import data
      community.mysql.mysql_db:
        name: all
        login_user: root
        login_password: RoboShop@1
        login_host: mysql.pract.site
        state: import
        target: "{{ item }}"
      loop:
      - /app/db/schema.sql
      - /app/db/app-user.sql
      - /app/db/master-data.sql

    - name: restart shipping
      ansible.builtin.service:
        name: shipping
        state: restarted
    


