      
      - name: app setup
        include_role:
          name: common
          tasks_from: app_setup
      
      - name: nodejs setup
        include_role:
          name: common
          tasks_from: nodejs

      - name: system setup
        include_role:
          name: common
          tasks_from: systemd

      - name: copy mongo repo
        ansible.builtin.copy:
          src: mongo.repo
          dest: /etc/yum.repos.d/mongo.repo

      - name: install mongodb-mongosh
        ansible.builtin.dnf:
          name: mongodb-mongosh
          state: installed

      - name: check products loaded or not
        ansible.builtin.command: mongosh --host {{ mongodb_host }} --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
        register: catalogue_output

      - name: print catalogue output
        ansible.builtin.debug:
          msg: "{{ catalogue_output }}"

      - name: loading the products
        ansible.builtin.shell: mongosh --host {{ mongodb_host }} </app/db/master-data.js
        when: catalogue_output.stdout | int < 0
        ignore_errors: true